//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 01:45:30 PM GMT+01:00 
//

package org.selfbus.sbhome.model.action;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import org.selfbus.sbhome.model.Namespaces;

/**
 * An action that sends a telegram to a group.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = Namespaces.PROJECT)
public class SendTelegramActionDecl extends AbstractActionDecl
{
   @XmlAttribute(name = "group")
   protected String group;

   @XmlAttribute(name = "value")
   protected String value;

   /**
    * Gets the value of the group property.
    * 
    * @return possible object is {@link String }
    * 
    */
   public String getGroup()
   {
      return group;
   }

   /**
    * Sets the value of the group property.
    * 
    * @param group allowed object is {@link String }
    * 
    */
   public void setGroup(String group)
   {
      this.group = group;
   }

   /**
    * Gets the value of the value property.
    * 
    * @return possible object is {@link String }
    * 
    */
   public String getValue()
   {
      return value;
   }

   /**
    * Sets the value of the value property.
    * 
    * @param value allowed object is {@link String }
    * 
    */
   public void setValue(String value)
   {
      this.value = value;
   }
}
